### ISSUE TITLE
Update to Keycloak 26.0.2

### ISSUE THREAD

**Issue by JonasDev17** [fschick/Keycloak.RestApiClient#10]
Keycloak version 26.0.2 introduces comprehensive OpenAPI documentation for the organization endpoints. Updating the library to this version ensures compatibility with the latest organization features.

https://www.keycloak.org/docs-api/latest/rest-api/index.html#_organizations

**Comment by fschick** [comment]
Done, release [26.0.2](https://github.com/fschick/Keycloak.RestApiClient/releases/tag/26.0.2)
