### ISSUE TITLE
Is this API realm querying users intentional?

### ISSUE THREAD

**Issue by srad** [fschick/Keycloak.RestApiClient#12]
I just looked at following example in the readme:

```
...

var credentials = new ClientCredentialsFlow
{
    KeycloakUrl = "https://<keycloak-url>",
    Realm = "<realm>", <---------------------------------
    ClientId = "<client-id>",
    ClientSecret = "<client-secret>"
};

using var httpClient = AuthenticationHttpClientFactory.Create(credentials);
using var usersApi = ApiClientFactory.Create<UsersApi>(httpClient);

var users = await usersApi.GetUsersAsync("<realm>"); <-------------------------
...
```

Is it intentional that you specify the `realm` twice?

**Comment by fschick** [comment]
I don't think so. I'll have a closer look tomorrow. Thank you for report this.

**Comment by fschick** [comment]
It's intentional. The realm used in `ClientCredentialsFlow` is the realm to login to. The realm used as parameter in `GetUsersAsync` is the realm to be modified. These realms can differ.
