### ISSUE TITLE
Create Realm: Fails with 'Unable to read content from stream'

### ISSUE THREAD

**Issue by cluen** [fschick/Keycloak.RestApiClient#4]
Hello,

tried to use `RealmsAdminApi` to create a new realm via Keycloak REST API.

First tried it with:
`ApiClientFactory.Create<RealmsAdminApi>(httpClient);`
but the url's which are generated are wrong. Because of the automatically added `"/admin/realms/"` in ApiClientFactory: `new Configuration { BasePath = $"{httpClient.KeycloakUrl}/admin/realms" },` the endpoints for PostAsync is wrong. Ends in: `"/admin/realms/admin/realms"` .

So tried it with:
`new RealmsAdminApi(httpClient, new FS.Keycloak.RestApiClient.Client.Configuration() { BasePath = <url> });`

with this ApiClient the resulting url's are correct. If I post a new RealmRepresentation to this endpoint, I get an ApiException:
`Error calling Post: {"errorMessage":"unable to read contents from stream"}"`

**Version Infos:**
Tried it with version:
23.* and the new 24.*

KeyCloak is in version: 24.*

**Comment by cluen** [comment]
Maybe it helps. If I remove certain properties from the JSON send to the API the realm is created.

```
{
	"id": "test",
	"realm": "test",
	"displayName": "test",
	"displayNameHtml": "<div class=\"kc-logo-text\"><span>test</span></div>",
	"notBefore": 0,
	"revokeRefreshToken": false,
	"refreshTokenMaxReuse": 0,
	"enabled": true,
	"passwordCredentialGrantAllowed": false,
	"registrationAllowed": true,
	"registrationEmailAsUsername": true,
	"rememberMe": true,
	"verifyEmail": true,
	"loginWithEmailAllowed": true,
	"duplicateEmailsAllowed": false,
	"resetPasswordAllowed": true,
	"editUsernameAllowed": true,
	"loginTheme": "keycloak",
	"eventsEnabled": false,
	"eventsExpiration": 0,
	"adminEventsEnabled": false,
	"adminEventsDetailsEnabled": false,
	"internationalizationEnabled": true,
	"supportedLocales": [
		"de",
		"en"
	],
	"defaultLocale": "de",
	"userManagedAccessAllowed": false,
	"social": false
}
```

In the documentation i've seen a File input for the Endpoint, but JSON still works.
Can't find any error in logoutput from keycloak. Maybe it is a problem with requestsize or content length or something.

**Comment by cluen** [comment]
Some addtitional infos, i've found:

The api has "duplicate" properties in different casings:
```
oAuth2DeviceCodeLifespan
oAuth2DevicePollingInterval

and (notice the A - a in Auth)
oauth2DeviceCodeLifespan
oauth2DevicePollingInterval
```

and if I don't send the properties, it works's (both properties are marked as deprecated [RealmRepresentation.java](https://github.com/keycloak/keycloak/blob/8e48bac27875888d218d8dbafc71c60f20277562/core/src/main/java/org/keycloak/representations/idm/RealmRepresentation.java#L89))
```
userCacheEnabled
realmCacheEnabled
```

**Comment by fschick** [comment]
Works fine without the properties. Thank you very much. Can you test is and close the issue on success?

**Comment by cluen** [comment]
Yes, thx. That work's for me!
Great and fast work 🚀
