### ISSUE TITLE
Properties like e.g. ClientRepresentation.Enabled are no longer nullable

### ISSUE THREAD

**Issue by candritzky** [fschick/Keycloak.RestApiClient#6]
We have a problem with version 24.0.1 of the library which we did not have with e.g. 22.0.3.
Most (if not all) of the properties are no longer nullable types.

Examples:
- RealmRepresentation.AccessTokenLifespan
- ClientRepresentation.Enabled

I think this is a bug in the generated code because they are not marked as required in [openapi.json](https://www.keycloak.org/docs-api/latest/rest-api/openapi.json).

AFAIK in OpenAPI everything is optional unless explicitly marked as required.

**Comment by fschick** [comment]
Recognized. Maybe it's a bug, I've updated the client generator with Keycloak 24. I will have a look next week.

**Comment by fschick** [comment]
Tried to fix. Could you check against 24.0.2-beta1?

**Comment by candritzky** [comment]
@fschick Thanks, looks good now and works.

**Comment by fschick** [comment]
24.0.2 released.
